[package]
name = "minibage-cli"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[build-dependencies]
capnpc = "0.19.0"


[dependencies]
capnp = "0.19.6"
clap = { version = "4.5.16", features = ["derive"] }
serialport = "4.5.0"
smart-leds = "0.4.0"
smart-leds-trait = "0.3.0"
